2022-09-24 11:12:21,074 - fishTrade_main20220913.py[line:559] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-24 11:12:21,074 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=eth_usdt highPrice=1700.0 lowPrice=1500.0  step_num=70.0
2022-09-24 11:12:22,964 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:12:24,974 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:12:26,835 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:12:28,850 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:12:30,640 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:12:32,642 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:12:34,514 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:12:36,524 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:12:38,357 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:12:40,358 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:12:42,351 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

